---
Build Image:
  image: debian:bookworm
  parallel:
    matrix:
      - IMAGE: [rhel9]
  variables:
    PACKER_LOG: '0'
  before_script:
    - apt update && apt install -qq curl qemu-system linux-image-amd64 libguestfs-tools packer rsync -y --no-install-recommends --no-install-suggests > /dev/null
  script:
    - packer build "${IMAGE}.pkr.hcl"
    - bash .gitlab/upload-packages.sh
  interruptible: true
